# Generated by Django 2.2.24 on 2021-07-30 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='fk_hab',
            new_name='nom_hab',
        ),
    ]
