# Generated by Django 2.2.24 on 2021-07-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitaciones',
            name='image',
            field=models.ImageField(default='', upload_to='habitaciones'),
            preserve_default=False,
        ),
    ]
