# Generated by Django 2.2.24 on 2021-07-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habitaciones', '0002_auto_20210726_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='rut_hab',
            new_name='num_hab',
        ),
    ]
